### ISSUE TITLE
[BUG] revealjs speaker view black screen

### ISSUE THREAD

**Issue by apmyplol** [jeertmans/manim-slides#449] opened 2024-06-17 09:55 UTC
### Description

When using the speaker view after exporting the presentation to HTML, the next slide preview and current slide windows are black. The notes however are visible.
Moreorver there are no errors in the web browser console, I think there could be some error with the iframe link for the preview window.

### Version

5.1.7

### Platform

Linux

**Comment by jeertmans** [comment] 2024-06-17 11:20
Hello @apmyplol! Thank you for posting this bug / question.

I should probably document it: this is not a bug, but rather a limitation from RevealJS.
For some reason, RevealJS decided not to play videos in the preview window, which is a shame for Manim Slides, as each slide is just a plain background video.

You could probably create a feature request on https://github.com/hakimel/reveal.js and ask if they can add an option to play background videos in the previewer.

I am closing this here as this is not related to Manim Slides (I cannot do anything here), but feel free to re-open this if there is any update from RevealJS on that regard!

**Closed by jeertmans** 2024-06-17 11:20 UTC
Labels: bug
