### ISSUE TITLE
[BUG] Invalid value for '--folder': Directory 'slides' does not exist.

### ISSUE THREAD

**Issue by ManimLearn** [jeertmans/manim-slides#461] opened 2024-08-07 03:43 UTC
Hi, I have just download manim slides and try out a simple example, but I've run into this problem. How can I fix it? Thank you. 
![screenshot_1723002060](https://github.com/user-attachments/assets/974d140d-41ec-4001-b8c5-e0d4b1799d93)

**Comment by jeertmans** [comment] 2024-08-07 05:45
Hello! This error, while not clear, indicates that you did not render the animations first, as rendering the animations should create that missing folder. Can you confirm?

**Comment by jeertmans** [comment] 2024-08-07 09:53
@ManimLearn looks like the rendering process did not end very well (despite the `code=0`).

Can you include the full command and terminal output here? Not just the end.

**Comment by ManimLearn** [comment] 2024-08-07 09:58
@jeertmans 
Here is the full terminal output. To rendered the scene I use Manim Slideview so I just Ctrl + S.


Manim Extension XTerm
Serves as a terminal for logging purpose.

Extension Version 0.2.13

MSV c:\Users\Admin>"manim" "c:\Users\Admin\Thuyết minh nckh.py" thuyetminhNCKH
Manim Community v0.18.1

[08/07/24 16:57:25] INFO     Animation 0 : Using cached    cairo_renderer.py:88
                             data (hash :                                      
                             3977891868_2543504905_2231324                     
                             57)                                               
[08/07/24 16:57:26] INFO     Animation 1 : Using cached    cairo_renderer.py:88         it/s]
                             data (hash :                                      
                             2852726489_1653248266_2105569                     
                             795)                                              
                    INFO     Combining to Movie file.  scene_file_writer.py:617     it/s]
                    INFO                               scene_file_writer.py:737
                             File ready at                                     
                             'C:\Users\Admin\media\vid                         
                             --- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\logging.py", line 170, in emit
    self.console.print(log_renderable)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\console.py", line 1673, in print
    with self:
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\console.py", line 865, in __exit__
    self._exit_buffer()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\console.py", line 823, in _exit_buffer
    self._check_buffer()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\console.py", line 2027, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u1ebf' in position 8: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Scripts\manim.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\manim\cli\render\commands.py", line 120, in render
    scene.render()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\manim\scene\scene.py", line 239, in render
    self.renderer.scene_finished(self)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\manim\renderer\cairo_renderer.py", line 269, in scene_finished
    self.file_writer.finish()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\manim\scene\scene_file_writer.py", line 457, in finish
    self.combine_to_movie()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\manim\scene\scene_file_writer.py", line 667, in combine_to_movie
    self.print_file_ready_message(str(movie_file_path))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\manim\scene\scene_file_writer.py", line 737, in print_file_ready_message
    logger.info("\nFile ready at %(file_path)s\n", {"file_path": f"'{file_path}'"})
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1539, in info
    self._log(INFO, msg, args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1028, in handle
    self.emit(record)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\logging.py", line 172, in emit
    self.handleError(record)
Message: '\nFile ready at %(file_path)s\n'
Arguments: {'file_path': "'C:\\Users\\Admin\\media\\videos\\Thuy\u1ebft minh nckh\\1080p60\\thuyetminhNCKH.mp4'"}
                    INFO                               scene_file_writer.py:737
                             File ready at                                     
                             'C:\Users\Admin\media\vid                         
                             --- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\logging.py", line 170, in emit
    self.console.print(log_renderable)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\console.py", line 1673, in print
    with self:
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\console.py", line 865, in __exit__
    self._exit_buffer()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\console.py", line 823, in _exit_buffer
    self._check_buffer()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\console.py", line 2027, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u1ebf' in position 8: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Scripts\manim.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\manim\cli\render\commands.py", line 120, in render
    scene.render()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\manim\scene\scene.py", line 247, in render
    logger.info(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1539, in info
    self._log(INFO, msg, args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1684, in _log
    self.handle(record)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1028, in handle
    self.emit(record)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\logging.py", line 172, in emit
    self.handleError(record)
Message: 'Rendered thuyetminhNCKH\nPlayed 2 animations'
Arguments: ()

**Comment by jeertmans** [comment] 2024-08-07 10:05
As you can read in the terminal output, you have an error rendering the animations, that starts at:

```
File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u1ebf' in position 8: character maps to
Call stack:
```

This is very likely caused by your string, as it contains non utf-8 characters.
Maybe you can try to *wrap* your strings with "my_string".encode("utf-8")?

I will close this issue as this is more related to Manim, or even Rich (which is used to print to the console), rather than Manim Slides.

**Closed** 2024-08-07 10:05 UTC
Labels: bug, duplicate, present
