### ISSUE TITLE
[BUG] Could not load multimedia backend "ffmpeg" (NixOS)

### ISSUE THREAD

**Issue by sierpinskiii** [jeertmans/manim-slides#340] opened 2023-12-17 10:07 UTC
### Could not load multimedia backend "ffmpeg"

I strongly believe this is rather not a bug but my mere misunderstanding of how manim-slides work, but let me explain this because it can be related with the reproducibility of the package installation.

When I execute `manim-slides BasicExample`, it give me the following message:
```
could not load multimedia backend "ffmpeg"
QtMultimedia is not currently supported on this platform or compiler.
Failed to create QVideoSink "Not available"
Failed to initialize QMediaPlayer "Not available"
```
I thought this is the problem coming from the absence of `ffmpeg` or `qt5`, so I installed them globally on my system. However, the problem persists.

### Version

manim-slides, version 5.0.0

### Platform

NixOS 23.05.
If this issue gets solved, I'm interested in packaging the `manim-slides`  for NixOS.
I personally think `manim-slides` would work a lot better with system level package manager (apt, dnf, pacman, etc), due to its heavy dependency on various software frameworks.

**Comment by jeertmans** [comment] 2023-12-17 11:18
Hello, you are right that dependencies can become very hard to manage, especially on OSes like yours.

Is NixOS Linux based? I would have guessed that it support the manylinux binaries, but maybe not.
As you can read, the Qt plug-in for displaying multimedia does not seem to be available on your platform.. I might be good to first investigate that issue further

**Comment by sierpinskiii** [comment] 2023-12-18 03:00
Right, NixOS is Linux based. So I think there might not be some specific issue that can cause the malfunction of the Qt multimedia plug-in.
Is manim-slides specifically depending on qt5? I tried both qt5 and qt6 on my system, but it didn't work properly.
If there is a Dockerfile for manim-slides, I might be able to investigate the issue by comparing the Dockerfile's setup procedure and that of my system.

**Comment by sierpinskiii** [comment] 2023-12-18 03:02
Also, I'd like to mention that someone proposed the packaging of manim-slides for the NixOS package manager, but looks like there is no significant progress for a few months, so it might be a good idea for us to resume the packaging.

**Comment by jeertmans** [comment] 2023-12-18 07:53
Creating a working Dockerfile is an ongoing issue but I didn’t time yet to work on that…

Qt is a required dependency for the present mode (+ wizard). 
What I don’t know is whether the issue is from Qt, or from PySide6 bindings. Maybe you can try using PyQt6. For that, I might need to rewrite the code so people can chose the bindings they prefer.

**Comment by jeertmans** [comment] 2023-12-18 09:28
Just a side note:

> I thought this is the problem coming from the absence of ffmpeg or qt5, so I installed them globally on my system. However, the problem persists.

Starting with v5.1, also waiting next Manim release (to be in sync), Manim Slides and Manim should not depend on a global FFMPEG installation anymore, because we will use PyAV that ships the necessary bindings. PySide6 should also ship `ffmpeg` bindings itself, I think.

**Comment by jeertmans** [comment] 2023-12-18 09:35
Regarding your issue, can you try installing `PyQt6` and see if you can import the multimedia module?

E.g., run this (change the video file path):

```python
import sys
from PyQt6.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget, QPushButton, QSlider
from PyQt6.QtMultimedia import QMediaPlayer
from PyQt6.QtMultimediaWidgets import QVideoWidget
from PyQt6.QtCore import QUrl, Qt


class VideoPlayer(QMainWindow):
    def __init__(self):
        super().__init__()

        self.setWindowTitle("Video Player")
        self.setGeometry(100, 100, 1024, 768)

        self.media_player = QMediaPlayer()
        self.media_player.setSource(QUrl.fromLocalFile("Video.mp4"))

        self.video_widget = QVideoWidget()

        self.start_button = QPushButton("Start")
        self.start_button.clicked.connect(self.start_video)

        self.pause_button = QPushButton("Pause")
        self.pause_button.clicked.connect(self.pause_video)

        self.stop_button = QPushButton("Stop")
        self.stop_button.clicked.connect(self.stop_video)

        self.slider = QSlider(Qt.Orientation.Horizontal)
        self.slider.sliderMoved.connect(self.set_position)

        self.media_player.setVideoOutput(self.video_widget)
        self.media_player.positionChanged.connect(self.position_changed)
        self.media_player.durationChanged.connect(self.duration_changed)

        layout = QVBoxLayout()
        layout.addWidget(self.video_widget)
        layout.addWidget(self.start_button)
        layout.addWidget(self.pause_button)
        layout.addWidget(self.stop_button)
        layout.addWidget(self.slider)

        container = QWidget()
        container.setLayout(layout)
        self.setCentralWidget(container)

    def start_video(self):
        self.media_player.play()

    def pause_video(self):
        self.media_player.pause()

    def stop_video(self):
        self.media_player.stop()

    def set_position(self, position):
        self.media_player.setPosition(position)

    def position_changed(self, position):
        self.slider.setValue(position)

    def duration_changed(self, duration):
        self.slider.setRange(0, duration)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    video_player = VideoPlayer()
    video_player.show()
    sys.exit(app.exec())
```

**Comment by dmadisetti** [comment] 2024-03-22 23:20
I got this to work with nixpkgs: https://github.com/NixOS/nixpkgs/pull/298198

no problem using ffmpe[g](https://www.youtube.com/watch?v=9kaIXkImCAM)

with this env
`nix-shell -p ffmpeg manim "python3.withPackages(ps: with ps; [ marimo manim-slides ])"`
even got magics working in a new type of notebook:
https://static.marimo.app/static/manim-example-rket

**Comment by jeertmans** [comment] 2024-03-25 13:29
So I am not sure to catch everything: is the original issue solved?

Nonetheless, I didn't know about the "new type of notebook" thing, and this might be nice to document it in the docs. Do you have some reference for this?

**Comment by dmadisetti** [comment] 2024-03-25 14:13
It should be fine once the nixpkgs PR is merged

As far as the new notebook, it's not widely used or even known about- I'm slowly moving over from Jupyter because I like it, and hope it takes off.
The project is called Marimo, and hopes to address some of the state-based pains that Jupyter brings: https://marimo.io/
Also really polished widgets, nicer UI, and feels less bloated

If you want to highlight what is possible in documentation, I'm sure they would appreciate it. I think this issue from the lead: https://github.com/marimo-team/marimo/issues/794
shows they have some interested in deeper integration with manim like tools - but what I did is a bit of a magics hack

**Comment by jeertmans** [comment] 2024-03-26 10:38
Nice!

Thanks for the link to Marimo's docs, I'll give it a look once I have some time :-)

**Comment by dmadisetti** [comment] 2024-04-03 16:56
nixos has now packaged `manim-slides`, should be in cache and widely accessible in a few days

**Comment by jeertmans** [comment] 2024-04-03 20:34
Great news! Thanks for your work @dmadisett!

**Comment by jeertmans** [comment] 2024-04-04 12:43
@dmadisetti, before I close this, would you mind adding a small section about how to install Manim Slides via NixOS in https://github.com/jeertmans/manim-slides/blob/main/docs/source/installation.md?

If you have time, I would really appreciate! I can review your PR and make some changes on top of it :-) Thanks!

**Comment by dmadisetti** [comment] 2024-04-04 15:23
No problem! I will once this gets into unstable cache, this should then get officially supported in 24.05 (released sometime in May)

**Comment by jeertmans** [comment] 2024-04-05 07:04
> No problem! I will once this gets into unstable cache, this should then get officially supported in 24.05 (released sometime in May)

thanks!

**Closed** 2024-04-11 07:30 UTC
Labels: bug, waiting author, installation, qt
