### ISSUE TITLE
[FEATURE] Add Interactive Feature in manimgl via manim-slides

### ISSUE THREAD

**Issue by semikernel** [jeertmans/manim-slides#469] opened 2024-09-03 16:06 UTC
### Terms

- [X] Checked the [existing issues](https://github.com/jeertmans/manim-slides/issues?q=is%3Aissue+label%3Adocumentation+) and [discussions](https://github.com/jeertmans/manim-slides/discussions) to see if my issue had not already been reported;

### Description

[manimgl](https://github.com/3b1b/manim.git) has interactive interface, I can press 'd' to rotate scene and 'r'  back to origin view. There are also mouse and keyboard interactive methods. I am wondering that if manim-slides could has the same effect using manimgl. After all, it's so cool to have an interactive ppt. Thx a lot:)

**Comment by jeertmans** [comment] 2024-09-03 16:26
Hello @semikernel, I think you already asked the same question in #380 :-)

Unfortunately, this is not possible, for one mine reason: interactivity provided by ManimGL is because video are (re-)renderer in live. Manim Slides, works after rendering, not during.

Moreover, ManimGL is not very well maintained, and trying to provide a compatibility layer with niche feature would require tremendous work.

Maybe there is a future where this will be possible, but this is very far with the current goals of this project, and would not be compatible with PowerPoint or HTML exports anyway.

**Comment by semikernel** [comment] 2024-09-05 10:22
> Hello @semikernel, I think you already asked the same question in #380 :-)
> 
> Unfortunately, this is not possible, for one mine reason: interactivity provided by ManimGL is because video are (re-)renderer in live. Manim Slides, works after rendering, not during.
> 
> Moreover, ManimGL is not very well maintained, and trying to provide a compatibility layer with niche feature would require tremendous work.
> 
> Maybe there is a future where this will be possible, but this is very far with the current goals of this project, and would not be compatible with PowerPoint or HTML exports anyway.

Thank you for your patience and clear explanation! I forgot that issue,  sorry for that mistake:)

**Comment by jeertmans** [comment] 2024-09-05 10:28
No problem, I will close this issue as this is a duplicate of #380, and it won't be fixed in the near feature :-)

**Closed by jeertmans** 2024-09-05 10:28 UTC
Labels: duplicate, enhancement, not planned
