### ISSUE TITLE
[BUG] Segmentation fault when presenting slides

### ISSUE THREAD

**Issue by pacaunt** [jeertmans/manim-slides#454] opened 2024-07-05 19:15 UTC
### Description

I run the basic example file with the command including manim and 
```
manim-slides BasicExample
```
but then the interface crashed and the following error appeared:
```
QOpenGLFunctions created with non-current context
[1]    9459 segmentation fault (core dumped)  manim-slides BasicExample

```
I use python 3.12.3  in a virtual environment on Ubuntu 24.04.

### Version

5.1.7

### Platform

Ubuntu 24.04 linux

**Comment by jeertmans** [comment] 2024-07-05 22:33
Hello! This is the first time I encounter this issue, so I do not know yet the solution.

Are you running the command inside a Docker environment or WSL?

Can you include the output of `pip freeze` here?

**Comment by pacaunt** [comment] 2024-07-06 04:29
> Hello! This is the first time I encounter this issue, so I do not know yet the solution.
> 
> Are you running the command inside a Docker environment or WSL?
> 
> Can you include the output of `pip freeze` here?

There is no output from that command...

**Comment by jeertmans** [comment] 2024-07-06 08:41
> > Hello! This is the first time I encounter this issue, so I do not know yet the solution.
> > Are you running the command inside a Docker environment or WSL?
> > Can you include the output of `pip freeze` here?
> 
> There is no output from that command...

Very bizarre, can you put a screenshot of you writing that in the terminal and the output here?

**Comment by pacaunt** [comment] 2024-07-06 12:40
[](url)
![Screenshot from 2024-07-06 19-38-58](https://github.com/jeertmans/manim-slides/assets/157231794/8e55bef2-caca-4349-bf7c-48f160af33db)
I run the Ubuntu by itself, not in WSL.

**Comment by jeertmans** [comment] 2024-07-06 12:44
> ![Screenshot from 2024-07-06 19-38-58](https://private-user-images.githubusercontent.com/157231794/346274111-8e55bef2-caca-4349-bf7c-48f160af33db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNzAxNDksIm5iZiI6MTcyMDI2OTg0OSwicGF0aCI6Ii8xNTcyMzE3OTQvMzQ2Mjc0MTExLThlNTViZWYyLWNhY2EtNDM0OS1iZjdjLTQ4ZjE2MGFmMzNkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQxMjQ0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODc1ZmZlZThkOGY2ZWYwN2RmY2MxYmM0NjQwMjhlN2Q4ZmFmMmI4NzVjMzgxMTMzOTdlZmIzM2VkMjVkZDcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mVjp_mwdh3RlB_6JYZoaISQQmKPg_SOpI4j5pCFUHR0) I run the Ubuntu by itself, not in WSL.

I meant a screenshot of the pip freeze command :)

**Comment by pacaunt** [comment] 2024-07-06 17:03
![Screenshot from 2024-07-07 00-02-35](https://github.com/jeertmans/manim-slides/assets/157231794/73deb88a-e579-49a7-bd84-b2f38155a73c)
There's really nothing... ToT

**Comment by jeertmans** [comment] 2024-07-07 03:08
Does not make any sense to me… Is pip working with other subcommands?

**Comment by bswck** [comment] 2024-07-13 02:39
I reproduced this with the following virtual environment:

<details>

```shell
annotated-types==0.7.0
av==12.2.0
certifi==2024.7.4
charset-normalizer==3.3.2
click==8.1.7
click-default-group==1.2.4
cloup==3.0.5
decorator==5.1.1
glcontext==2.5.0
idna==3.7
isosurfaces==0.1.2
jinja2==3.1.4
lxml==5.2.2
manim==0.18.1
manim-slides==5.1.7
manimpango==0.5.0
mapbox-earcut==1.0.1
markdown-it-py==3.0.0
markupsafe==2.1.5
mdurl==0.1.2
moderngl==5.10.0
moderngl-window==2.4.6
multipledispatch==1.0.0
networkx==3.3
numpy==1.26.4
packaging==24.1
pillow==10.4.0
pycairo==1.26.1
pydantic==2.8.2
pydantic-core==2.20.1
pydantic-extra-types==2.9.0
pydub==0.25.1
pyglet==2.0.15
pygments==2.18.0
pyrr==0.10.3
pyside6==6.7.2
pyside6-addons==6.7.2
pyside6-essentials==6.7.2
python-pptx==0.6.23
qtpy==2.4.1
requests==2.32.3
rich==13.7.1
rtoml==0.11.0
scipy==1.14.0
screeninfo==0.8.1
shiboken6==6.7.2
skia-pathops==0.8.0.post1
srt==3.5.3
svgelements==1.9.6
tqdm==4.66.4
typing-extensions==4.12.2
urllib3==2.2.2
watchdog==4.0.1
xlsxwriter==3.2.0
```

</details>

Output when compiling the example:

```bash
❯ manim-slides BasicExample
[AVHWDeviceContext @ 0x3a34f00] libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[AVHWDeviceContext @ 0x3a37340] libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
QOpenGLFunctions created with non-current context
Segmentation fault (core dumped)
```

**Comment by bswck** [comment] 2024-07-13 03:00
Downgrading to `pyside6==6.5.2` fixed the issue. CC @pacaunt 
@jeertmans maybe re-pin pyside6 to take that into account?

**Comment by jeertmans** [comment] 2024-07-18 17:09
Hello @bswck, thanks for the update! However, PySide6 is not available on Python 3.12, at least not if installed via Pip, see the [Python requires](https://pypi.org/project/PySide6/6.5.2/). What version are your using?

**Comment by jeertmans** [comment] 2024-09-11 13:19
Closing as not responses from author, feel free to re-open if you think this is still an issue.

**Closed by jeertmans** 2024-09-11 13:19 UTC
Labels: bug, waiting author, qt, python-3.12, linux

**Comment by FloezeTv** [comment] 2024-10-30 20:07
Hey @jeertmans,

I think I am experiencing the same issue that is already identified in this thread.

When I run `manim-slides BasicExample`, the GUI starts, but is frozen, and then crashes with a segmentation-fault:
```console
$ manim-slides BasicExample
[h264 @ 0x563c0a901fc0] Failed to allocate a vaapi/nv12 frame from a fixed pool of hardware frames.
[h264 @ 0x563c0a901fc0] Consider setting extra_hw_frames to a larger value (currently set to -1, giving a pool size of 36).
[h264 @ 0x563c0a901fc0] get_buffer() failed
[h264 @ 0x563c0a901fc0] thread_get_buffer() failed
[h264 @ 0x563c0a901fc0] decode_slice_header error
[h264 @ 0x563c0a901fc0] no frame!
QOpenGLFunctions created with non-current context
zsh: segmentation fault (core dumped)  manim-slides BasicExample
```
The part about failing to allocate a vaapi/nv12 frame does not always appear (on my CachyOS machine it did not appear at all):
```console
$ manim-slides BasicExample
QOpenGLFunctions created with non-current context
zsh: segmentation fault (core dumped)  manim-slides BasicExample
```
It did not matter, whether I installed using `pipx` or in a python `venv` and whether I selected `pyside6-full` or `pyqt6-full`.

<details>
  <summary><code>pip freeze</code></summary>

  ```
  annotated-types==0.7.0
  asttokens==2.4.1
  av==13.1.0
  certifi==2024.8.30
  charset-normalizer==3.4.0
  click==8.1.7
  click-default-group==1.2.4
  cloup==3.0.5
  decorator==5.1.1
  docutils==0.21.2
  executing==2.1.0
  glcontext==3.0.0
  idna==3.10
  ipython==8.29.0
  isosurfaces==0.1.2
  jedi==0.19.1
  Jinja2==3.1.4
  lxml==5.3.0
  manim==0.18.1
  manim-slides==5.1.9
  ManimPango==0.6.0
  mapbox_earcut==1.0.2
  markdown-it-py==3.0.0
  MarkupSafe==3.0.2
  matplotlib-inline==0.1.7
  mdurl==0.1.2
  moderngl==5.12.0
  moderngl-window==2.4.6
  multipledispatch==1.0.0
  networkx==3.4.2
  numpy==1.26.4
  packaging==24.1
  parso==0.8.4
  pexpect==4.9.0
  pillow==11.0.0
  prompt_toolkit==3.0.48
  ptyprocess==0.7.0
  pure_eval==0.2.3
  pycairo==1.27.0
  pydantic==2.9.2
  pydantic-extra-types==2.9.0
  pydantic_core==2.23.4
  pydub==0.25.1
  pyglet==2.0.18
  Pygments==2.18.0
  pyrr==0.10.3
  PySide6==6.8.0.2
  PySide6_Addons==6.8.0.2
  PySide6_Essentials==6.8.0.2
  python-pptx==1.0.2
  QtPy==2.4.1
  requests==2.32.3
  rich==13.9.3
  rtoml==0.11.0
  scipy==1.14.1
  screeninfo==0.8.1
  shiboken6==6.8.0.2
  six==1.16.0
  skia-pathops==0.8.0.post2
  srt==3.5.3
  stack-data==0.6.3
  svgelements==1.9.6
  tqdm==4.66.6
  traitlets==5.14.3
  typing_extensions==4.12.2
  urllib3==2.2.3
  watchdog==5.0.3
  wcwidth==0.2.13
  XlsxWriter==3.2.0
  ```
</details>

I followed the example from the [Quickstart](https://manim-slides.eertmans.be/latest/quickstart.html) and can reproduce this error on both Manjaro with Python 3.12.6 and CachyOS with Python 3.12.7.

**Comment by jeertmans** [comment] 2024-10-30 22:09
Hi @FloezeTv, thanks for reporting! I will re-open.

Can you test if the issue persists PyQT6 instead of PySide6? And with version 6.7.*?

**Comment by FloezeTv** [comment] 2024-10-31 17:22
Yes, the issue occurs with both `pyqt6` (installing `manim-slides` using `pyqt6-full`) as well as with older versions of `pyside6` (I've tested `6.7.3`, `6.7.0`, `6.6.3.1`, and `6.6.0`).

**Comment by jeertmans** [comment] 2024-11-01 08:24
> Downgrading to `pyside6==6.5.2` fixed the issue. CC @pacaunt @jeertmans maybe make an extra with pyside6 pinned to 6.5.2?

@FloezeTv and what about version `6.5.2`?

> Yes, the issue occurs with both `pyqt6` (installing `manim-slides` using `pyqt6-full`) as well as with older versions of `pyside6` (I've tested `6.7.3`, `6.7.0`, `6.6.3.1`, and `6.6.0`).

Thanks for testing!

**Comment by FloezeTv** [comment] 2024-11-01 08:53
I downgraded python to `3.11.9` and `manim-slides` works with `pyside6==6.5.2`.
`pyside6==6.5.3` is broken again, however:
```console
qt.multimedia.ffmpeg.libsymbolsresolver: Couldn't load OpenSsl library
    failed to get textures for frame; format: 44 textureConverter null
QOpenGLFunctions created with non-current context
zsh: segmentation fault (core dumped)  manim-slides BasicExample
```

**Comment by jeertmans** [comment] 2024-11-01 10:26
Do you have `libva` installed? https://github.com/intel/libva

See relevant thread: https://forum.qt.io/topic/150877/qt-multimedia-warnings-qt-6-6-0/8

**Comment by FloezeTv** [comment] 2024-11-01 11:44
Yes, `libva` is installed.
I also found that thread when searching for that error.
I did not get the `Couldn't load VAAPI library`-message, so I think `libva` should be working properly.
The line about OpenSSL is because I have OpenSSL 3 installed and QT looks for OpenSSL 1.1 I think (as is also written in that thread).

**Comment by jeertmans** [comment] 2024-11-01 15:57
> I downgraded python to `3.11.9` and `manim-slides` works with `pyside6==6.5.2`. `pyside6==6.5.3` is broken again, however:
> 
> ```
> qt.multimedia.ffmpeg.libsymbolsresolver: Couldn't load OpenSsl library
>     failed to get textures for frame; format: 44 textureConverter null
> QOpenGLFunctions created with non-current context
> zsh: segmentation fault (core dumped)  manim-slides BasicExample
> ```

If I remember correctly, 6.5.3 introduced some bugs. Does 6.6 and 6.7 versions work on Python 3.11?
